// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIfZPCIwj07Gfxi423iH8cImkU1XMCLRc',
    appId: '1:382827134847:web:2653ef86c3e71d84e2a44a',
    messagingSenderId: '382827134847',
    projectId: 'incos-check',
    authDomain: 'incos-check.firebaseapp.com',
    storageBucket: 'incos-check.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtTWVEejH77fYXDkU78ZZ0ggZFfD6hydM',
    appId: '1:382827134847:android:e4e710b7a29ff555e2a44a',
    messagingSenderId: '382827134847',
    projectId: 'incos-check',
    storageBucket: 'incos-check.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYrGUOxzH5EK8RMI9yhOnBYpWqwRDgEu0',
    appId: '1:382827134847:ios:d1add92c5536217ae2a44a',
    messagingSenderId: '382827134847',
    projectId: 'incos-check',
    storageBucket: 'incos-check.firebasestorage.app',
    iosBundleId: 'com.example.incosCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYrGUOxzH5EK8RMI9yhOnBYpWqwRDgEu0',
    appId: '1:382827134847:ios:d1add92c5536217ae2a44a',
    messagingSenderId: '382827134847',
    projectId: 'incos-check',
    storageBucket: 'incos-check.firebasestorage.app',
    iosBundleId: 'com.example.incosCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIfZPCIwj07Gfxi423iH8cImkU1XMCLRc',
    appId: '1:382827134847:web:93dee2b0af977693e2a44a',
    messagingSenderId: '382827134847',
    projectId: 'incos-check',
    authDomain: 'incos-check.firebaseapp.com',
    storageBucket: 'incos-check.firebasestorage.app',
  );
}
